'''
    Description:
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

a_1, a_2 = 1, 2
sum = 2
while a_2 < 4_000_000:
    n_x = a_1 + a_2
    a_1 = a_2
    a_2 = n_x
    if n_x%2 == 0:
        sum += n_x

print(sum)